Add three featured data articles and images
PASTAplus/content-x pull request #19
Opened 2022-03-29 19:44 UTC by kzollove

This PR adds Featured Data articles from July, September, and November 2021

2022-03-30 14:44 UTC, clnsmth commented on templates/data/featured-jul-2021.md
> +### Featured Data Packages
Should be "Citation"

2022-03-30 14:45 UTC, clnsmth commented on templates/data/featured-jul-2021.md
> +1. Borer, E.T., W.S. Harpole, P.B. Adler et al. 2020. Data from nutrients cause grassland biomass to outpace herbivory, 2008-2019 ver 1. Environmental Data Initiative. [https://doi.org/10.6073/pasta/
Space separate the citations, not enumerated list

2022-03-30 14:46 UTC, clnsmth commented on templates/data/featured-jul-2021.md
> +
Missing section header "Description"

2022-03-30 14:48 UTC, clnsmth commented on templates/data/featured-nov-2021.md
> +Sheehan, N. and L. Weber-Grullon. 2021. Journey North – Hummingbird observations by volunteer community scientists across Central and North America (1996-2020) ver 1. Environmental Data Initiative. [
Should be new line separated.

2022-03-30 14:50 UTC, clnsmth commented on templates/data/featured-sep-2021.md
> +
Missing "Description" header

2022-03-30 14:57 UTC, clnsmth commented on templates/data/news-211102a.md
> +# news-tags
Thanks for including these. Please move to the bottom of the page and wrap in HTML comment tags `<!-- a normal html comment -->`

2022-03-30 14:58 UTC, clnsmth commented on templates/data/news-211102a.md
> +# date
Use the same date format as featured data

2022-03-30 14:59 UTC, clnsmth commented on templates/data/news-211102a.md
> +# news-tags
Use the title "News" on line 1 as done on featured data pages.

2022-03-30 15:00 UTC, clnsmth commented on templates/data/news-211102a.md
> +# Updates to user-contributed journal citation interface on the EDI Data Portal
Second title on the page should be the article title. Again similar to featured data

2022-03-30 15:01 UTC, clnsmth commented on templates/data/news-211102b.md
> +# news-tags
Same comments of news-211202*.md apply to this and subsequent files

2022-03-30 15:02 UTC, clnsmth requested changes
Thanks @kzollove. A couple requested changes.

- Try getting the image file size below 200 KB. Maybe compress again?
- Apply file name format of featured data to news items
- Some formatting tweaks, noted in the files

2022-03-30 18:19 UTC, kzollove commented
Formatting tweaks have been implemented across the board.

Images: It doesn't look like I can get the PNG size down further with tinypng. I can compress more if I use JPEG. Should I replace PNGs with JPEGs where they are larger than 200 KB?

Name format: How should I go about this (there are multiple news articles from the same month, some even from the same day) Possible: news-month-yyyy.md or news-day-month-yyyy, how to indicate different within month or day? news-month-yyyy-a.md, news-month-yyyy-1.md, etc?

2022-03-31 13:06 UTC, clnsmth commented
Thanks @kzollove. 
* .jpgs work and if for some reason that doesn't do the trick, try resizing. 
* For dates across all articles (news, blog, featured) let's use `[articletype]-YYYYMMDDhhmm.md`. Reason being (just remembering this now) is that article management (storage and posting) will be determined by publication date. If there isn't a hhmm, fabricate one. : )

2022-03-31 13:39 UTC, kzollove commented
@clnsmth thanks for the feedback.

All formatting tweaks implemented.
All images in the featured and news articles are <200 KB
All filenames are now formatted as `[articletype]-YYYYMMDDhhmm.md`

2022-04-01 17:16 UTC, merged